<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(): Response
    {
        $user = $this->getUser();
        if ($user && $user->isPasswordAutoGenerated()) {
            return $this->redirectToRoute('app_change_password', ['username' => $user->getUsername()]);
        }
        
        return $this->render('home/home.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
    
}
