<?php
// src/Controller/HomeController.php

namespace App\Controller;

use App\Entity\Announcement;
use App\Entity\UserCourseAccess;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function home(Request $request, ManagerRegistry $doctrine): Response
    {
        // 0) Not logged in? → login
        $user = $this->getUser();
        if (null === $user) {
            return $this->redirectToRoute('app_login');
        }

        // 0.5) Password was auto-generated → force change
        // (avoid infinite loop if your change_password route also uses this controller)
        if (method_exists($user, 'isPasswordAutoGenerated') && $user->isPasswordAutoGenerated()) {
            return $this->redirectToRoute('app_change_password');
        }

        $em            = $doctrine->getManager();
        $recentCourses = [];
        $announcements = [];

        // 1) Recent courses
        $accessRepo     = $em->getRepository(UserCourseAccess::class);
        $recentAccesses = $accessRepo->findBy(
            ['user' => $user],
            ['accessedAt' => 'DESC'],
            5
        );
        foreach ($recentAccesses as $access) {
            $recentCourses[] = $access->getCourse();
        }

        // 2) Latest announcements
        $annRepo       = $em->getRepository(Announcement::class);
        $announcements = $annRepo->findBy(
            [],
            ['createdAt' => 'DESC'],
            5
        );

        return $this->render('home/home.html.twig', [
            'recentCourses' => $recentCourses,
            'announcements' => $announcements,
        ]);
    }
}
