<?php

namespace App\EventSubscriber;

use App\Entity\User;
use App\Entity\Role;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class AdminUserSubscriber implements EventSubscriberInterface
{
    private EntityManagerInterface $entityManager;
    private UserPasswordHasherInterface $passwordHasher;
    private static bool $initialized = false;

    public function __construct(EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher)
    {
        $this->entityManager   = $entityManager;
        $this->passwordHasher  = $passwordHasher;
    }

    public function onKernelRequest(RequestEvent $event): void
    {
        //Exécuter une seule fois par cycle de requête
        if (self::$initialized) {
            return;
        }
        self::$initialized = true;

        $em = $this->entityManager;

        // 1) Trouver ou créer l'entité de rôle ROLE_ADMIN
        $roleRepo = $em->getRepository(Role::class);
        $adminRole = $roleRepo->findOneBy(['name' => 'ROLE_ADMIN']);
        if (!$adminRole) {
            $adminRole = new Role();
            $adminRole->setName('ROLE_ADMIN');
            $em->persist($adminRole);
            // Ne pas effectuer de flush pour l'instant, attendre après la persistance de l'utilisateur
        }

        // 2) Trouver ou créer l'utilisateur admin
        $adminEmail = 'admin@coursly.com';
        $userRepo   = $em->getRepository(User::class);
        $adminUser  = $userRepo->findOneBy(['email' => $adminEmail]);

        if (!$adminUser) {
            $adminUser = new User();
            $adminUser->setEmail($adminEmail);
            $adminUser->setUsername('admin_coursly');
            $adminUser->setFirstName('Admin');
            $adminUser->setLastName('User');

            // Hacher et définir le mot de passe
            $plainPassword   = 'admincoursly';
            $hashedPassword  = $this->passwordHasher->hashPassword($adminUser, $plainPassword);
            $adminUser->setPassword($hashedPassword);

            // Marquer que ce mot de passe n'a pas été généré automatiquement
            $adminUser->setPasswordAutoGenerated(false);

            // Attribuer le rôle ROLE_ADMIN
            $adminUser->addRole($adminRole);

            $em->persist($adminUser);
        } else {
            // S'assurer que l'admin existant possède également le rôle ROLE_ADMIN
            if (!in_array('ROLE_ADMIN', $adminUser->getRoles(), true)) {
                $adminUser->addRole($adminRole);
            }
        }

        // 3) Effectuer le flush à la fois pour le rôle et l'utilisateur en une seule opération
        $em->flush();
    }

    public static function getSubscribedEvents(): array
    {
        return [
            'kernel.request' => ['onKernelRequest', 0],
        ];
    }
}
